                                         Creating array with an existing array

In [1]:
from numpy import *

In [5]:
arr = array([1,2,3,4,5])

# I want to add 5 to each and every element
arr1 = arr + 5
print('Befor adding 5 to every elements',arr)
print('After adding 5 to every elements',arr1)

Befor adding 5 to every elements [1 2 3 4 5]
After adding 5 to every elements [ 6  7  8  9 10]


In [7]:
#we can also add 2 different arrays
arr1= array([1,2,3,4,5])
arr2 =array([6,1,9,3,2])

arr3 = arr1+arr2
print('array 1                   :',arr1)
print('array 2                   :',arr2)
print('Additionf of arr1 and arr2:',arr3)

array 1                   : [1 2 3 4 5]
array 2                   : [6 1 9 3 2]
Additionf of arr1 and arr2: [ 7  3 12  7  7]


 -- numppy : num stands for numerical value, we can do certain operations
 
 -- example : trignometry operations (sin,cos,tan)

In [16]:
#Find sin of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('sin values of array element:',sin(arr))

Original array             : [1 2 3 4 5]
sin values of array element: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [17]:
#Find cos of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('cos values of array element:',cos(arr))

Original array             : [1 2 3 4 5]
cos values of array element: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [18]:
#Find log of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('log values of array element:',log(arr))

Original array             : [1 2 3 4 5]
log values of array element: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [19]:
#Find square root of array
arr = array([1,2,3,4,5])
print('Original array              :',arr)
print('sqrt values of array element:',sqrt(arr))

Original array              : [1 2 3 4 5]
sqrt values of array element: [1.         1.41421356 1.73205081 2.         2.23606798]


In [20]:
#Find sum of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('sum values of array element:',sum(arr))

Original array             : [1 2 3 4 5]
sum values of array element: 15


In [21]:
#Find min of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('min values of array element:',min(arr))

Original array             : [1 2 3 4 5]
min values of array element: 1


In [22]:
#Find max of array
arr = array([1,2,3,4,5])
print('Original array             :',arr)
print('max values of array element:',max(arr))

Original array             : [1 2 3 4 5]
max values of array element: 5


In [25]:
#sorting array 
arr=array([5,7,4,3,9])
print('Original array:',arr)
print('sorting array :',sort(arr))

Original array: [5 7 4 3 9]
sorting array : [3 4 5 7 9]


In [26]:
#unique values
arr=array([5,7,4,3,9,7,3,6,1])
print('Original array            :',arr)
print('unique values in the array:',unique(arr))

Original array            : [5 7 4 3 9 7 3 6 1]
unique values in the array: [1 3 4 5 6 7 9]


In [28]:
#concatenate array
arr1= array([1,2,3,4,5])
arr2 =array([6,1,9,3,2])
print('array 1           :',arr1)
print('array 2           :',arr2)
print('concatenated array:',concatenate([arr1,arr2]))


array 1           : [1 2 3 4 5]
array 2           : [6 1 9 3 2]
concatenated array: [1 2 3 4 5 6 1 9 3 2]


                                      How to copy an array?

In [29]:
arr1=array([2,5,8,3,0,5])
arr2=arr1
print(arr1)
print(arr2)

[2 5 8 3 0 5]
[2 5 8 3 0 5]


In [30]:
#But in your memory you'll have only one array, not 2 array, array 2 is not backup of array 1
#How to check, like this :
arr1=array([2,5,8,3,0,5])
arr2=arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
#both the arrays pointing to same address

[2 5 8 3 0 5]
[2 5 8 3 0 5]
2005143060368
2005143060368


In [31]:
#then comes the concept of aliasing
arr1=array([2,5,8,3,0,5])
arr2 = arr1.view() #to store the values in 2 different address
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
#both address are different but there is a one problem here

[2 5 8 3 0 5]
[2 5 8 3 0 5]
2005143458160
2005143458832


____________________________________________________________________________________________________________________________


 
 when copying also we have 2 different copies:
<li> Shallow Copy
<li> Deep Copy

<li> Shallow Copy : It will copy the elements but then , both array still depends on each other

In [32]:
arr1=array([2,5,8,3,0,5])
arr2 = arr1.view() # shallow copy
arr1[1]=7 # changing value of array 1 2nd element 
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

#since we are doing shallow copy, if we change array 1 it will change in array 2 as well, hence 2 arrays depend on each other

[2 7 8 3 0 5]
[2 7 8 3 0 5]
2005143060368
2005143458928


In [33]:
arr1=array([2,5,8,3,0,5])
arr2 = arr1.view() # shallow copy
arr2[1]=7 # changing value of array 2 2nd element 
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
#since we are doing shallow copy, if we change array 2 it will change in array 1 as well, hence 2 arrays depend on each other

[2 7 8 3 0 5]
[2 7 8 3 0 5]
2005143458736
2005143458160


<li> Deep Copy : wont depend one each other

In [34]:
arr1=array([2,5,8,3,0,5])
arr2 = arr1.copy() # Deep copy
arr2[1]=7 # changing value of array 2 2nd element 
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
#It chaged whatever array element we changed array 1 element remains the same here

[2 5 8 3 0 5]
[2 7 8 3 0 5]
2005143060368
2005143459120


In [36]:
arr1=array([2,5,8,3,0,5])
arr2 = arr1.copy() # Deep copy
arr1[1]=7 # changing value of array 2 2nd element 
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 7 8 3 0 5]
[2 5 8 3 0 5]
2005143458640
2005143459216
