                                                          MULTI DIMENSIONAL ARRAY

In [2]:
from numpy import *

In [3]:
#Inside one array have 2 array
arr = array([
    [1,2,3],
    [4,5,6]
])#2 dimensional array creation
print(arr)
print(arr.dtype)
print(arr.ndim)#no of dimension
print(arr.shape) # no of rows and column
print(arr.size)

[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
6


In [7]:
#Inside one array have 2 array
arr = array([
    [1,2,3],
    [4,5,6]
])#2 dimensional array creation
print('Array before converting:\n',arr)
## arr1 is 3 dimensional array convert into 1 dimensional array
arr2=arr.flatten() # flatten() function will make2 dimensional array to 1 dimensional
print('Array after converting:\n',arr2)


Array before converting:
 [[1 2 3]
 [4 5 6]]
Array after converting:
 [1 2 3 4 5 6]


In [10]:
#converting single dimensional to multi-dimensional
#Inside one array have 2 array
arr1 = array([
    [1,2,3,6,2,9],
    [4,5,6,7,5,3]
])#2 dimensional array creation
print("Two dimensional Array:\n",arr1)
arr2 = arr1.flatten() # flatten() function will make2 dimensional array to 1 dimensional
print("After converting to One dimensional Array:\n",arr2)
arr3=arr2.reshape(3,4) #reshape conerts one dimensional array to 2 dimensional array, reshape(no of rows, no of columns)
print("After converting one dimensional array to 2 dimensional array:\n",arr3)


Two dimensional Array:
 [[1 2 3 6 2 9]
 [4 5 6 7 5 3]]
After converting to One dimensional Array:
 [1 2 3 6 2 9 4 5 6 7 5 3]
After converting one dimensional array to 2 dimensional array:
 [[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [11]:
#what if we have big array, in which we have 2D array : Create 3D array
#Inside one array have 2 array
arr1 = array([
    [1,2,3,6,2,9],
    [4,5,6,7,5,3]
])#2 dimensional array creation
print("Two dimensional Array:\n",arr1)
arr2 = arr1.flatten() # flatten() function will make2 dimensional array to 1 dimensional
print("After converting to One dimensional Array:\n",arr2)
arr3=arr2.reshape(2,2,3)# reshape(2 Two dimensional array, 2 single dimensional array,Thre values)  
print("After converting one dimensional array to three dimensional array:\n",arr3)

Two dimensional Array:
 [[1 2 3 6 2 9]
 [4 5 6 7 5 3]]
After converting to One dimensional Array:
 [1 2 3 6 2 9 4 5 6 7 5 3]
After converting one dimensional array to three dimensional array:
 [[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [17]:
#Mathematics
arr1 = array([
    [1,2,3,6],
    [4,5,6,7]
])#Tow dimensional array creation
print("Two dimensional Array:\n",arr1)
m = matrix(arr1)
print('m also contain same array that we created :\n',m) #This 'm' is used for different matrix operation

Two dimensional Array:
 [[1 2 3 6]
 [4 5 6 7]]
m also contain same array that we created :
 [[1 2 3 6]
 [4 5 6 7]]


In [19]:
#Another way of creating matrics array
m=matrix('1 2 3 6 ; 4 5 6 7') # 2 rows 2 columns here
print(m) # if the input given by user , matrix() function will create the array

[[1 2 3 6]
 [4 5 6 7]]


In [20]:
m=matrix('1 2 ; 3 6 ; 4 5 ; 6 7') # 4 rows 2 columns here
print(m) # if the input given by user , matrix() function will create the array

[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [24]:
m=matrix('1 2 3 ; 6 4 5 ; 1 6 7') # 2 rows 2 columns here
print('Printing Array:\n',m) # if the input given by user , matrix() function will create the array

# what if I want toprint only diagonal elements
print('Printing diagonal element:\n',diagonal(m))

Printing Array:
 [[1 2 3]
 [6 4 5]
 [1 6 7]]
Printing diagonal element:
 [1 4 7]


In [26]:
#what if I want to run a minimum element from matrix
m=matrix('1 2 3 ; 6 4 5 ; 1 6 7') # 2 rows 2 columns here
print('Printing Array:\n',m) # if the input given by user , matrix() function will create the array
print('Minimum value inside matrix:\n',m.min())

Printing Array:
 [[1 2 3]
 [6 4 5]
 [1 6 7]]
Minimum value inside matrix:
 1


In [28]:
#what if I want to run a maximum element from matrix
m=matrix('1 2 3 ; 6 4 5 ; 1 6 7') # 2 rows 2 columns here
print('Printing Array:\n',m) # if the input given by user , matrix() function will create the array
print('Maximum value inside matrix:\n',m.max())

Printing Array:
 [[1 2 3]
 [6 4 5]
 [1 6 7]]
Maximum value inside matrix:
 7


In [29]:
#Adding matrix
m1=matrix('1 2 3 ; 6 4 5 ; 1 6 7')
print('First matrix:\n',m1) 
m2=matrix('1 2 3 ; 6 8 5 ; 2 6 7')
print('Second matrix:\n',m2) 
m3=m1+m2
print('Addition of 2 matrices:\n',m3)

First matrix:
 [[1 2 3]
 [6 4 5]
 [1 6 7]]
Second matrix:
 [[1 2 3]
 [6 8 5]
 [2 6 7]]
Addition of 2 matrices:
 [[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [30]:
#Multipling matrix
m1=matrix('1 2 3 ; 6 4 5 ; 1 6 7')
print('First matrix:\n',m1) 
m2=matrix('1 2 3 ; 6 8 5 ; 2 6 7')
print('Second matrix:\n',m2) 
m3=m1 * m2
print('Mltiplication of 2 matrices:\n',m3)

First matrix:
 [[1 2 3]
 [6 4 5]
 [1 6 7]]
Second matrix:
 [[1 2 3]
 [6 8 5]
 [2 6 7]]
Mltiplication of 2 matrices:
 [[19 36 34]
 [40 74 73]
 [51 92 82]]
