                                                       NUMPY

6 ways of creating arrays 
<li>array()
<li>linespace()
<li>logspace()
<li>arange()
<li>zeros()
<li>ones()

_______________________________________________________________________________________________________________________________

<li>array()

In [24]:
from numpy import *

In [25]:
arr = array([2,4,6,7,8])
print(arr)

[2 4 6 7 8]


In [26]:
arr = array([2,4,6,7,8])
print(arr.dtype) # getting type of array
print(arr)

int64
[2 4 6 7 8]


In [27]:
from array import *

#you can also create array like this 
arr = array('i',[2,4,6,7,8])
print(arr)

array('i', [2, 4, 6, 7, 8])


In [28]:
# another way of creating array
from numpy import *
arr = array([2,4,6,7,8],int) # we also create like this by giving datatype
print(arr.dtype)
print(arr)

int64
[2 4 6 7 8]


_______________________________________________________________________________________________________________________________

<li> linspace() : here when compared to logspace() gap between 2 elements are fixed

In [33]:
# way of creating array using linespace() function
from numpy import *
#linspace(start,end(inculded),no of parts)
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [34]:
arr = linspace(0,15,20) # it will part values into 20
print(arr)

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [35]:
#if you don't specify the parts , no of parst would be 50
arr = linspace(0,15)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


_______________________________________________________________________________________________________________________________

<li> arange()

In [38]:
# way of creating array using arange() function
from numpy import *
# arange(start,end(excluded last one),steps to skip the number)
arr = arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


_______________________________________________________________________________________________________________________________

<li> logspace() : here when compared to linspace() , spacing would be log of it 

In [40]:
# way of creating array using logspace() function
from numpy import *
#logspace(start,end,5 parts)
arr = logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [43]:
arr = logspace(1,40,5)
#showing all below print statements how the value could be display
print(arr[0])
print(arr[4])
print('%.2f' %arr[4])

10.0
1e+40
10000000000000000303786028427003666890752.00


______________________________________________________________________________________________________________________________

<li> zeros() : if you ant to create an array of size 10, all the values by default would be zero

In [45]:
from numpy import *
arr = zeros(5)
print(arr)  # float value

[0. 0. 0. 0. 0.]


In [46]:
#to get the output in iteger format
arr = zeros(5, int)
print(arr)  # integer value

[0 0 0 0 0]


________________________________________________________________________________________________________________________________

<li> ones() : : if you ant to create an array of size 10, all the values by default would be one

In [47]:
from numpy import *
arr = ones(5)
print(arr)  # float value

[1. 1. 1. 1. 1.]


In [48]:
#to get the output in iteger format
arr = ones(5, int)
print(arr)  # integer value

[1 1 1 1 1]
